name: "CICD practice"

on: 
  pull_request: 
    branches:
    - main
    - master

jobs:
  run-Go:
    runs-on: ubuntu-latest
    steps:
      - name: "run the go code"
        run: echo 'hello world after a long time'
  


